#List
* list can be defined as a collection of values or items of different types. 
* Python lists are mutable type
* order are fixed

In [ ]:
list1 = [1, 2, "Python", "Program", 15.9]    
print(list1)  
print(type(list1))

[1, 2, 'Python', 'Program', 15.9]
<class 'list'>

##Indexing and slicing 
* it is similar to string's indexing and slicing

## Python List Operations
* Repetition
* Concatenation
* Length
* Iteration
* Membership

In [ ]:
# Repetition
print('Repetition')
list1=[2,3,4,5,6]
print(list1*2)
print('-------------------------------------')
# Concatenation
print('Concatenation')
list2=[7,3,9,1]
print(list1+list2)
print('-------------------------------------')
# Length
print('length')
print(len(list1))
print('-------------------------------------')
# iteration
print('iteration')
for i in list1:
  print(i)
print('-------------------------------------')
# membership
print('membership')
a=7 in list2
print(a)
print('-------------------------------------')

Repetition
[2, 3, 4, 5, 6, 2, 3, 4, 5, 6]
-------------------------------------
Concatenation
[2, 3, 4, 5, 6, 7, 3, 9, 1]
-------------------------------------
length
5
-------------------------------------
iteration
2
3
4
5
6
-------------------------------------
membership
True
-------------------------------------

## Add Element or remove element
* add by using append() , extend() , insert() method
* remove by using remove() , clear() , pop() method 
* In remove method we are passing value not index
* In pop method we are passing index
----------------------------------------------
### some more methods
* sort()
* index()
* count()
* reverse()

In [ ]:
print('add element')
list1=[6,2,8,1]
list1.append(int(input()))
print(list1)
print('-------------------------------------')
print('remove element')
list1.remove(6)
print(list1)

add element
9
[6, 2, 8, 1, 9]
-------------------------------------
remove element
[2, 8, 1, 9]

## Built in Function
* len()
* max()
* min()

# Tuple
* list and tuple are similar but lists are mutable, tuples are immutable
* tuples are ordered like lists
* tuple is created by using parenthesis
* tuple is created by using without parenthesis
* single element in tuple treated as string
* Tuples are unchangeable but we can change agar hum phle list mein convert kr le fir usko tuple mein kr le
* we have only 2 method count() , index()

In [ ]:
# tuple is created by using parenthesis
tuple1 = (4, "Python", 9.3)   
# we can also create without using parenthesis
tuple2 = 4, 5.7, "Tuples" 
# single element in tuple treated as string
single_tuple = ("Tuple")    
print( type(tuple1) )
print( type(tuple2) )  
print( type(single_tuple) )

<class 'str'>
<class 'tuple'>
<class 'tuple'>

# Sets
* A set is a collection which is unordered, unchangeable*, and unindexed.
* Duplicates Not Allowed
* Although  sets are unchangeable but we can update or remove element

In [10]:
set1 = {1,2,3, "JavaTpoint", 20.5, 14}  
print(set1)
print(type(set1))

{1, 'JavaTpoint', 3, 2, 20.5, 14}
<class 'set'>

In [11]:
# add element
set1.add('python')
print(set1)

{1, 'JavaTpoint', 3, 2, 20.5, 14, 'python'}


* clear() -->    Removes all the elements from the set 
* pop()   -->   	Removes an element from the set
* remove() -->    Removes the specified element
* discard() ->    Remove the specified item
** remove and discard are similar

In [12]:
# pop
print('pop')
set1.pop()
print(set1)
print('----------------------------------------')
# remove
print('remove')
set1.remove(2)
print(set1)
print('----------------------------------------')
# discard
print('discard')
set1.discard('python')
print(set1)
print('----------------------------------------')
# clear
print('clear')
set1.clear()
print(set1)

pop
{'JavaTpoint', 3, 2, 20.5, 14, 'python'}
----------------------------------------
remove
{'JavaTpoint', 3, 20.5, 14, 'python'}
----------------------------------------
discard
{'JavaTpoint', 3, 20.5, 14}
----------------------------------------
clear
set()

-------------------------------------------------------
* intersection
* union

In [13]:
set1={2,8,5,3,9}
set2={8,6,1,2}
set3=set1.intersection(set2)
print('intersection')
print(set3)
set4=set1.union(set2)
print('union')
print(set4)

intersection
{8, 2}
union
{1, 2, 3, 5, 6, 8, 9}

------------------------------------------------------------------------
* isdisjoint()	Returns whether two sets have a intersection or not
* issubset()	Returns whether another set contains this set or not
* issuperset()	Returns whether this set contains another set or not

In [18]:
print('isdisjoint  of set1 and set2 -->' , set1.isdisjoint(set2)) # agar intersection hoga to false nhi to true
print('is set3 is subset of set1 --> ' , set3.issubset(set1))
print('is set1 is super set of set3 --> ' , set1.issuperset(set3))

isdisjoint  of set1 and set2 --> False
is set3 is subset of set1 -->  True
is set1 is super set of set3 -->  True

In [ ]:
# difference()
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.difference(y)

print(z)

# Dictionary
* Dictionaries are used to store data values in key:value pairs.
* A dictionary is a collection which is ordered*, changeable
* As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.
* Dictionaries are written with curly brackets, and have keys and values
* All key are always unique and Keys must only have one component. 
* values can be duplicates and Values can be of any type, including integer, list, and tuple.

In [21]:
dict1 = {1: 'Hcl', 2: 'WIPRO', 3:'Facebook'}
print(dict1) 
print(type(dict1))
print(len(dict1))

print('for all keys we use dict1.keys() --> ' , dict1.keys())
print('for all keys we use dict1.values() --> ' , dict1.values())

{1: 'Hcl', 2: 'WIPRO', 3: 'Facebook'}
<class 'dict'>
3
for all keys we use dict1.keys() -->  dict_keys([1, 2, 3])
for all keys we use dict1.values() -->  dict_values(['Hcl', 'WIPRO', 'Facebook'])

In [29]:
# Accessing
print(dict1[2])

dict2={"brand": "Ford", "model": "Mustang", "year": 1964}
print(dict2['brand'])
print('----------------------------------------')


# Accessing by using get keyword
print('Accessing by using get keyword')
print(dict2.get('model'))
print('----------------------------------------')

# by using item() method
print('by using item() method')
print(dict2.items())

WIPRO
Ford
Accessing by using get keyword
Mustang
by using item() method
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])

### Adding

In [33]:
# Adding elements to dictionary one at a time       
dict2[0] = 'Peter'      

# Adding multiple elements to dictionary one at a time   
dict2['Emp_ages'] = 20, 33, 24     

# Updating existing Key's Value       
dict2['year'] = 1924      


# Updating existing Key's Value by using update keyword       
dict2.update({'year': 1969})


print(dict2)

{'brand': 'Ford', 'model': 'Mustang', 'year': 69, 0: 'Peter', 'Emp_ages': (20, 33, 24)}

### remove

In [34]:
# by using pop method
dict2.pop("model")

# by using popitem() method
# popitem() ---->   Remove the last item 
dict2.popitem()

print(dict2)

{'brand': 'Ford', 'year': 69, 0: 'Peter'}